$('#exampleModal').on 'show.bs.modal', (event) ->
  button = $(event.relatedTarget)
  recipient = button.data('whatever')
  modal = $(this)
  modal.find('.modal-title').text 'New message to ' + recipient
  modal.find('.modal-body input').val recipient
  return

# ---
# generated by js2coffee 2.2.0